# **Author: Sri Sudheera Chitipolu**

### *Github: https://github.com/sudheera96*

## Acquire the Data

Collected data from kaggle

*https://www.kaggle.com/hellbuoy/car-price-prediction*

## General Description: 
For understanding pricing dynamics of the new market in the different cars for business growth, we will predict the carâ€™s prices depending on different independent variables.

## Importing the dataset

In [1]:
import pandas as pd # imported pandas as pd
cp_data = pd.read_csv("carPrice_Assignment.csv") # pulled data from csv file to pandas dataframe
print(cp_data.keys()) # display a list of the names of the fields
cp_data.head(10) # table display of the first few lines in the DataFrame

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.000
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.000
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.000
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.000
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.000
5,6,2,audi fox,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250.000
6,7,1,audi 100ls,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710.000
7,8,1,audi 5000,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920.000
8,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.000
9,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,17859.167

## _Notes_
In inital_exploration we have seen there are features with negative correlated with target variable. So we are droping them from data set

In [2]:
df = cp_data.drop(columns=["car_ID","CarName","highwaympg","citympg","peakrpm","symboling"])

In [3]:
df_obj_cols = df.select_dtypes(include = 'object')
df_num_cols = df.select_dtypes(exclude = 'object')
# make object columns to numerical columns using get_dummies
df_obj_dummies = pd.get_dummies(df_obj_cols,drop_first=True)
df_obj_dummies.head()

,fueltype_gas,aspiration_turbo,doornumber_two,carbody_hardtop,carbody_hatchback,carbody_sedan,carbody_wagon,drivewheel_fwd,drivewheel_rwd,enginelocation_rear,...,cylindernumber_three,cylindernumber_twelve,cylindernumber_two,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,1,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
1,1,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
2,1,0,1,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
3,1,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

## _Notes_

Created dummy variables for categorical without it with column in every respective dummy variable inorder to avoid multicollinarity.

In [4]:
final_cardf = pd.concat([df_num_cols, df_obj_dummies], axis=1)
final_cardf.head()

,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,...,cylindernumber_three,cylindernumber_twelve,cylindernumber_two,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,...,0,0,0,0,0,0,0,1,0,0
1,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,...,0,0,0,0,0,0,0,1,0,0
2,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,...,0,0,0,0,0,0,0,1,0,0
3,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,...,0,0,0,0,0,0,0,1,0,0
4,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,...,0,0,0,0,0,0,0,1,0,0

## _Notes_
Similary removed other features which are having negative correlation with price. For more details look at the initial exploration

In [5]:
final_cardf = final_cardf.drop(columns=["cylindernumber_four","drivewheel_fwd","fuelsystem_2bbl","enginetype_ohc",
                                        "carbody_hatchback",
                                        "fueltype_gas","cylindernumber_three","fuelsystem_spdi",
                                        "carbody_wagon","doornumber_two","fuelsystem_spfi","fuelsystem_4bbl",
                                        "enginetype_rotor","cylindernumber_two","fuelsystem_mfi"])

## Splitting the dataset to train set and test set.

Test set using as cross validation

In [6]:
from sklearn.model_selection import train_test_split
X = final_cardf.drop('price',1)
x_train, x_cv, y_train, y_cv = train_test_split(X,final_cardf.price, test_size =0.3)

#  outliers identified and removed with isolation forest

In [7]:
# evaluate model performance with outliers removed using isolation forest
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import IsolationForest
from sklearn.metrics import mean_absolute_error
# summarize the shape of the training dataset
print(x_train.shape, y_train.shape)
# identify outliers in the training dataset
iso = IsolationForest(contamination=0.1)
yhat = iso.fit_predict(x_train)
# select all rows that are not outliers
mask = yhat != -1
x_train1, y_train1 = x_train[mask], y_train[mask]
# summarize the shape of the updated training dataset
print(x_train1.shape, y_train1.shape)
# fit the model
model = LinearRegression()
model.fit(x_train1, y_train1)
# evaluate the model
yhat = model.predict(x_cv)
# evaluate predictions
mae = mean_absolute_error(y_cv, yhat)
print('MAE: %.3f' % mae)

(143, 24) (143,)
(129, 24) (129,)
MAE: 2498.619

In this case, we can see that the isolation forest method identified and removed only 14 outliers.

# elliptical envelope (minimum covariant determinant) method

In [8]:
from sklearn.covariance import EllipticEnvelope
print(x_train.shape, y_train.shape)
# identify outliers in the training dataset
ee = EllipticEnvelope(contamination=0.01)
yhat = ee.fit_predict(x_train)
# select all rows that are not outliers
mask = yhat != -1
x_train2, y_train2 = x_train[mask], y_train[mask]
# summarize the shape of the updated training dataset
print(x_train2.shape, y_train2.shape)
# fit the model
model = LinearRegression()
model.fit(x_train2, y_train2)
# evaluate the model
yhat = model.predict(x_cv)
# evaluate predictions
mae = mean_absolute_error(y_cv, yhat)
print('MAE: %.3f' % mae)

(143, 24) (143,)
(141, 24) (141,)
MAE: 2430.685

C:\tools\Anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:647: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn("The covariance matrix associated to your dataset "

In this case, we can see that the elliptical envelope method identified and removed only 2 outliers

# Local Outlier Factor

In [9]:
from sklearn.neighbors import LocalOutlierFactor
# summarize the shape of the training dataset
print(x_train.shape, y_train.shape)
# identify outliers in the training dataset
lof = LocalOutlierFactor()
yhat = lof.fit_predict(x_train)
# select all rows that are not outliers
mask = yhat != -1
x_train3, y_train3 = x_train[mask], y_train[mask]
# summarize the shape of the updated training dataset
print(x_train3.shape, y_train3.shape)
# fit the model
model = LinearRegression()
model.fit(x_train3, y_train3)
# evaluate the model
yhat = model.predict(x_cv)
# evaluate predictions
mae = mean_absolute_error(y_cv, yhat)
print('MAE: %.3f' % mae)

(143, 24) (143,)
(132, 24) (132,)
MAE: 2159.432

In this case, we can see that the local outliner factor method identified and removed only 13 outliers

# One-Class SVM

In [10]:
from sklearn.svm import OneClassSVM
# summarize the shape of the training dataset
print(x_train.shape, y_train.shape)
# identify outliers in the training dataset
ee = OneClassSVM(nu=0.01)
yhat = ee.fit_predict(x_train)
# select all rows that are not outliers
mask = yhat != -1
x_train4, y_train4 = x_train[mask], y_train[mask]
# summarize the shape of the updated training dataset
print(x_train4.shape, y_train4.shape)
# fit the model
model = LinearRegression()
model.fit(x_train4, y_train4)
# evaluate the model
yhat = model.predict(x_cv)
# evaluate predictions
mae = mean_absolute_error(y_cv, yhat)
print('MAE: %.3f' % mae)

(143, 24) (143,)
(143, 24) (143,)
MAE: 2609.678

In this case, we can see that the one class SVM method identified and removed only 0 outliers

# Linear Regression

In [11]:
# fit the model
model = LinearRegression()
model.fit(x_train, y_train)
# evaluate the model
yhat = model.predict(x_cv)
# evaluate predictions
mae = mean_absolute_error(y_cv, yhat)
print('MAE: %.3f' % mae)

MAE: 2609.678

By comparing the MAE of linear regression with all outliners detection methods we got local outliner detector with low MAE with removal of 13 outliners. So we can say there are 13 outliners which are not useful.